site_name: Typeix
site_url: https://typeix.com/
site_author: Igor Ivanovic
site_description: >-
  Fast, unopinionated, minimalist typescript framework for building efficient and scalable applications.
extra_css: [ ]
# Repository
repo_name: typeix
repo_url: https://github.com/typeix/typeix
docs_url: /getting-started
edit_uri: ""


# Copyright
copyright: Copyright &copy; 2016 - 2021 Igor Ivanovic

home:
  intro_section:
    h1: Hello, Typeix!
    description: Fast, unopinionated, minimalist framework for building efficient and scalable applications and libraries with typescript or javascript.
  badges:
    - title: EXTENSIBLE
      description: Provides flexibility by allowing use core libraries in own projects.
      icon: material/cogs
    - title: VERSATILE
      description: Adaptable ecosystem for all kinds of server-side applications or custom libraries.
      icon: material/auto-fix
    - title: LIGHTWEIGHT
      description: "@typeix/resty is a minimal and flexible Node.js web application framework that provides a robust set of features."
      icon: material/progress-wrench

  live_preview:
    h1: Live preview
    description: See how your application may potentially look.

theme:
  name: material
  custom_dir: theme
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: slate
      primary: red
      accent: red

  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/favicon.png
  logo: /assets/logo-inverted.png


# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_optional_attribute_quotes: false

# Customization
extra:
  twitter: typeixframework
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/typeix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/typeixframework
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/igorivanoviczg

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Documentation:
      - Getting Started: getting-started.md
      - Fundamentals:
        - Controllers: documentation/controllers.md
        - Modules: documentation/modules.md
        - Providers: documentation/providers.md
        - Interceptors: documentation/interceptors.md
        - Testing: documentation/testing.md
        - Model-View-Controller: documentation/model-view-controller.md

      - Databases:
          - RDBMS with TypeORM: documentation/type-orm.md
          - Mongodb with TypeORM: documentation/type-orm-mongo.md

      - "@typeix/packages":
          - "@typeix/metadata": packages/typeix-metadata.md
          - "@typeix/di": packages/typeix-di.md
          - "@typeix/modules": packages/typeix-modules.md
          - "@typeix/router": packages/typeix-router.md
          - "@typeix/logger": packages/typeix-logger.md
          - "@typeix/resty": packages/resty/typeix-resty.md

          # - AWS Lambda Adapter: packages/resty/typeix-resty-aws-lambda.md
  - Benchmarks: benchmarks.md
  - Roadmap: roadmap.md
# Google Analytics
google_analytics:
  - "G-CRNY5PJKJH"
  - auto
